/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutSabhaRouteImport } from './routes/about-sabha'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppealForBuildingConstructionRouteImport } from './routes/appeal-for-building-construction'
import { Route as CancellationRouteImport } from './routes/cancellation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DonateForSevasRouteImport } from './routes/donate-for-sevas'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as EpfoForm5aRouteImport } from './routes/epfo-form-5a'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as OurAchievementsRouteImport } from './routes/our-achievements'
import { Route as OurVisionRouteImport } from './routes/our-vision'
import { Route as PanchangamRouteImport } from './routes/panchangam'
import { Route as PatasalaDetailsRouteImport } from './routes/patasala-details'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RajasastrigalRouteImport } from './routes/rajasastrigal'
import { Route as SabhaRouteImport } from './routes/sabha'
import { Route as SabhaPatronsTrusteesRouteImport } from './routes/sabha-patrons-trustees'
import { Route as SourcesOfSustenanceRouteImport } from './routes/sources-of-sustenance'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VedaAshramamRouteImport } from './routes/veda-ashramam'
import { Route as VedaPatasalaRouteImport } from './routes/veda-patasala'
import { Route as VedabhavanRouteImport } from './routes/vedabhavan'
import { Route as WaysToSupportRouteImport } from './routes/ways-to-support'
import { Route as WhyVedaSamrakshanamRouteImport } from './routes/why-veda-samrakshanam'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSabhaRoute = AboutSabhaRouteImport.update({
  id: '/about-sabha',
  path: '/about-sabha',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealForBuildingConstructionRoute =
  AppealForBuildingConstructionRouteImport.update({
    id: '/appeal-for-building-construction',
    path: '/appeal-for-building-construction',
    getParentRoute: () => rootRouteImport,
  } as any)
const CancellationRoute = CancellationRouteImport.update({
  id: '/cancellation',
  path: '/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateForSevasRoute = DonateForSevasRouteImport.update({
  id: '/donate-for-sevas',
  path: '/donate-for-sevas',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const EpfoForm5aRoute = EpfoForm5aRouteImport.update({
  id: '/epfo-form-5a',
  path: '/epfo-form-5a',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const OurAchievementsRoute = OurAchievementsRouteImport.update({
  id: '/our-achievements',
  path: '/our-achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const OurVisionRoute = OurVisionRouteImport.update({
  id: '/our-vision',
  path: '/our-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const PanchangamRoute = PanchangamRouteImport.update({
  id: '/panchangam',
  path: '/panchangam',
  getParentRoute: () => rootRouteImport,
} as any)
const PatasalaDetailsRoute = PatasalaDetailsRouteImport.update({
  id: '/patasala-details',
  path: '/patasala-details',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RajasastrigalRoute = RajasastrigalRouteImport.update({
  id: '/rajasastrigal',
  path: '/rajasastrigal',
  getParentRoute: () => rootRouteImport,
} as any)
const SabhaRoute = SabhaRouteImport.update({
  id: '/sabha',
  path: '/sabha',
  getParentRoute: () => rootRouteImport,
} as any)
const SabhaPatronsTrusteesRoute = SabhaPatronsTrusteesRouteImport.update({
  id: '/sabha-patrons-trustees',
  path: '/sabha-patrons-trustees',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesOfSustenanceRoute = SourcesOfSustenanceRouteImport.update({
  id: '/sources-of-sustenance',
  path: '/sources-of-sustenance',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VedaAshramamRoute = VedaAshramamRouteImport.update({
  id: '/veda-ashramam',
  path: '/veda-ashramam',
  getParentRoute: () => rootRouteImport,
} as any)
const VedaPatasalaRoute = VedaPatasalaRouteImport.update({
  id: '/veda-patasala',
  path: '/veda-patasala',
  getParentRoute: () => rootRouteImport,
} as any)
const VedabhavanRoute = VedabhavanRouteImport.update({
  id: '/vedabhavan',
  path: '/vedabhavan',
  getParentRoute: () => rootRouteImport,
} as any)
const WaysToSupportRoute = WaysToSupportRouteImport.update({
  id: '/ways-to-support',
  path: '/ways-to-support',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyVedaSamrakshanamRoute = WhyVedaSamrakshanamRouteImport.update({
  id: '/why-veda-samrakshanam',
  path: '/why-veda-samrakshanam',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-sabha': typeof AboutSabhaRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/appeal-for-building-construction': typeof AppealForBuildingConstructionRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/donate-for-sevas': typeof DonateForSevasRoute
  '/downloads': typeof DownloadsRoute
  '/epfo-form-5a': typeof EpfoForm5aRoute
  '/gallery': typeof GalleryRoute
  '/our-achievements': typeof OurAchievementsRoute
  '/our-vision': typeof OurVisionRoute
  '/panchangam': typeof PanchangamRoute
  '/patasala-details': typeof PatasalaDetailsRoute
  '/privacy': typeof PrivacyRoute
  '/rajasastrigal': typeof RajasastrigalRoute
  '/sabha': typeof SabhaRoute
  '/sabha-patrons-trustees': typeof SabhaPatronsTrusteesRoute
  '/sources-of-sustenance': typeof SourcesOfSustenanceRoute
  '/terms': typeof TermsRoute
  '/veda-ashramam': typeof VedaAshramamRoute
  '/veda-patasala': typeof VedaPatasalaRoute
  '/vedabhavan': typeof VedabhavanRoute
  '/ways-to-support': typeof WaysToSupportRoute
  '/why-veda-samrakshanam': typeof WhyVedaSamrakshanamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-sabha': typeof AboutSabhaRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/appeal-for-building-construction': typeof AppealForBuildingConstructionRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/donate-for-sevas': typeof DonateForSevasRoute
  '/downloads': typeof DownloadsRoute
  '/epfo-form-5a': typeof EpfoForm5aRoute
  '/gallery': typeof GalleryRoute
  '/our-achievements': typeof OurAchievementsRoute
  '/our-vision': typeof OurVisionRoute
  '/panchangam': typeof PanchangamRoute
  '/patasala-details': typeof PatasalaDetailsRoute
  '/privacy': typeof PrivacyRoute
  '/rajasastrigal': typeof RajasastrigalRoute
  '/sabha': typeof SabhaRoute
  '/sabha-patrons-trustees': typeof SabhaPatronsTrusteesRoute
  '/sources-of-sustenance': typeof SourcesOfSustenanceRoute
  '/terms': typeof TermsRoute
  '/veda-ashramam': typeof VedaAshramamRoute
  '/veda-patasala': typeof VedaPatasalaRoute
  '/vedabhavan': typeof VedabhavanRoute
  '/ways-to-support': typeof WaysToSupportRoute
  '/why-veda-samrakshanam': typeof WhyVedaSamrakshanamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-sabha': typeof AboutSabhaRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/appeal-for-building-construction': typeof AppealForBuildingConstructionRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/donate-for-sevas': typeof DonateForSevasRoute
  '/downloads': typeof DownloadsRoute
  '/epfo-form-5a': typeof EpfoForm5aRoute
  '/gallery': typeof GalleryRoute
  '/our-achievements': typeof OurAchievementsRoute
  '/our-vision': typeof OurVisionRoute
  '/panchangam': typeof PanchangamRoute
  '/patasala-details': typeof PatasalaDetailsRoute
  '/privacy': typeof PrivacyRoute
  '/rajasastrigal': typeof RajasastrigalRoute
  '/sabha': typeof SabhaRoute
  '/sabha-patrons-trustees': typeof SabhaPatronsTrusteesRoute
  '/sources-of-sustenance': typeof SourcesOfSustenanceRoute
  '/terms': typeof TermsRoute
  '/veda-ashramam': typeof VedaAshramamRoute
  '/veda-patasala': typeof VedaPatasalaRoute
  '/vedabhavan': typeof VedabhavanRoute
  '/ways-to-support': typeof WaysToSupportRoute
  '/why-veda-samrakshanam': typeof WhyVedaSamrakshanamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-sabha'
    | '/activities'
    | '/admin'
    | '/appeal-for-building-construction'
    | '/cancellation'
    | '/contact'
    | '/donate'
    | '/donate-for-sevas'
    | '/downloads'
    | '/epfo-form-5a'
    | '/gallery'
    | '/our-achievements'
    | '/our-vision'
    | '/panchangam'
    | '/patasala-details'
    | '/privacy'
    | '/rajasastrigal'
    | '/sabha'
    | '/sabha-patrons-trustees'
    | '/sources-of-sustenance'
    | '/terms'
    | '/veda-ashramam'
    | '/veda-patasala'
    | '/vedabhavan'
    | '/ways-to-support'
    | '/why-veda-samrakshanam'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-sabha'
    | '/activities'
    | '/admin'
    | '/appeal-for-building-construction'
    | '/cancellation'
    | '/contact'
    | '/donate'
    | '/donate-for-sevas'
    | '/downloads'
    | '/epfo-form-5a'
    | '/gallery'
    | '/our-achievements'
    | '/our-vision'
    | '/panchangam'
    | '/patasala-details'
    | '/privacy'
    | '/rajasastrigal'
    | '/sabha'
    | '/sabha-patrons-trustees'
    | '/sources-of-sustenance'
    | '/terms'
    | '/veda-ashramam'
    | '/veda-patasala'
    | '/vedabhavan'
    | '/ways-to-support'
    | '/why-veda-samrakshanam'
  id:
    | '__root__'
    | '/'
    | '/about-sabha'
    | '/activities'
    | '/admin'
    | '/appeal-for-building-construction'
    | '/cancellation'
    | '/contact'
    | '/donate'
    | '/donate-for-sevas'
    | '/downloads'
    | '/epfo-form-5a'
    | '/gallery'
    | '/our-achievements'
    | '/our-vision'
    | '/panchangam'
    | '/patasala-details'
    | '/privacy'
    | '/rajasastrigal'
    | '/sabha'
    | '/sabha-patrons-trustees'
    | '/sources-of-sustenance'
    | '/terms'
    | '/veda-ashramam'
    | '/veda-patasala'
    | '/vedabhavan'
    | '/ways-to-support'
    | '/why-veda-samrakshanam'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutSabhaRoute: typeof AboutSabhaRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRoute
  AppealForBuildingConstructionRoute: typeof AppealForBuildingConstructionRoute
  CancellationRoute: typeof CancellationRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  DonateForSevasRoute: typeof DonateForSevasRoute
  DownloadsRoute: typeof DownloadsRoute
  EpfoForm5aRoute: typeof EpfoForm5aRoute
  GalleryRoute: typeof GalleryRoute
  OurAchievementsRoute: typeof OurAchievementsRoute
  OurVisionRoute: typeof OurVisionRoute
  PanchangamRoute: typeof PanchangamRoute
  PatasalaDetailsRoute: typeof PatasalaDetailsRoute
  PrivacyRoute: typeof PrivacyRoute
  RajasastrigalRoute: typeof RajasastrigalRoute
  SabhaRoute: typeof SabhaRoute
  SabhaPatronsTrusteesRoute: typeof SabhaPatronsTrusteesRoute
  SourcesOfSustenanceRoute: typeof SourcesOfSustenanceRoute
  TermsRoute: typeof TermsRoute
  VedaAshramamRoute: typeof VedaAshramamRoute
  VedaPatasalaRoute: typeof VedaPatasalaRoute
  VedabhavanRoute: typeof VedabhavanRoute
  WaysToSupportRoute: typeof WaysToSupportRoute
  WhyVedaSamrakshanamRoute: typeof WhyVedaSamrakshanamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-sabha': {
      id: '/about-sabha'
      path: '/about-sabha'
      fullPath: '/about-sabha'
      preLoaderRoute: typeof AboutSabhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal-for-building-construction': {
      id: '/appeal-for-building-construction'
      path: '/appeal-for-building-construction'
      fullPath: '/appeal-for-building-construction'
      preLoaderRoute: typeof AppealForBuildingConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation': {
      id: '/cancellation'
      path: '/cancellation'
      fullPath: '/cancellation'
      preLoaderRoute: typeof CancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate-for-sevas': {
      id: '/donate-for-sevas'
      path: '/donate-for-sevas'
      fullPath: '/donate-for-sevas'
      preLoaderRoute: typeof DonateForSevasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epfo-form-5a': {
      id: '/epfo-form-5a'
      path: '/epfo-form-5a'
      fullPath: '/epfo-form-5a'
      preLoaderRoute: typeof EpfoForm5aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-achievements': {
      id: '/our-achievements'
      path: '/our-achievements'
      fullPath: '/our-achievements'
      preLoaderRoute: typeof OurAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-vision': {
      id: '/our-vision'
      path: '/our-vision'
      fullPath: '/our-vision'
      preLoaderRoute: typeof OurVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panchangam': {
      id: '/panchangam'
      path: '/panchangam'
      fullPath: '/panchangam'
      preLoaderRoute: typeof PanchangamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patasala-details': {
      id: '/patasala-details'
      path: '/patasala-details'
      fullPath: '/patasala-details'
      preLoaderRoute: typeof PatasalaDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rajasastrigal': {
      id: '/rajasastrigal'
      path: '/rajasastrigal'
      fullPath: '/rajasastrigal'
      preLoaderRoute: typeof RajasastrigalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sabha': {
      id: '/sabha'
      path: '/sabha'
      fullPath: '/sabha'
      preLoaderRoute: typeof SabhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sabha-patrons-trustees': {
      id: '/sabha-patrons-trustees'
      path: '/sabha-patrons-trustees'
      fullPath: '/sabha-patrons-trustees'
      preLoaderRoute: typeof SabhaPatronsTrusteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources-of-sustenance': {
      id: '/sources-of-sustenance'
      path: '/sources-of-sustenance'
      fullPath: '/sources-of-sustenance'
      preLoaderRoute: typeof SourcesOfSustenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veda-ashramam': {
      id: '/veda-ashramam'
      path: '/veda-ashramam'
      fullPath: '/veda-ashramam'
      preLoaderRoute: typeof VedaAshramamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veda-patasala': {
      id: '/veda-patasala'
      path: '/veda-patasala'
      fullPath: '/veda-patasala'
      preLoaderRoute: typeof VedaPatasalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vedabhavan': {
      id: '/vedabhavan'
      path: '/vedabhavan'
      fullPath: '/vedabhavan'
      preLoaderRoute: typeof VedabhavanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ways-to-support': {
      id: '/ways-to-support'
      path: '/ways-to-support'
      fullPath: '/ways-to-support'
      preLoaderRoute: typeof WaysToSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-veda-samrakshanam': {
      id: '/why-veda-samrakshanam'
      path: '/why-veda-samrakshanam'
      fullPath: '/why-veda-samrakshanam'
      preLoaderRoute: typeof WhyVedaSamrakshanamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutSabhaRoute: AboutSabhaRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRoute,
  AppealForBuildingConstructionRoute: AppealForBuildingConstructionRoute,
  CancellationRoute: CancellationRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  DonateForSevasRoute: DonateForSevasRoute,
  DownloadsRoute: DownloadsRoute,
  EpfoForm5aRoute: EpfoForm5aRoute,
  GalleryRoute: GalleryRoute,
  OurAchievementsRoute: OurAchievementsRoute,
  OurVisionRoute: OurVisionRoute,
  PanchangamRoute: PanchangamRoute,
  PatasalaDetailsRoute: PatasalaDetailsRoute,
  PrivacyRoute: PrivacyRoute,
  RajasastrigalRoute: RajasastrigalRoute,
  SabhaRoute: SabhaRoute,
  SabhaPatronsTrusteesRoute: SabhaPatronsTrusteesRoute,
  SourcesOfSustenanceRoute: SourcesOfSustenanceRoute,
  TermsRoute: TermsRoute,
  VedaAshramamRoute: VedaAshramamRoute,
  VedaPatasalaRoute: VedaPatasalaRoute,
  VedabhavanRoute: VedabhavanRoute,
  WaysToSupportRoute: WaysToSupportRoute,
  WhyVedaSamrakshanamRoute: WhyVedaSamrakshanamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
